version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    container_name: "rails6"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails6_test
      - bundle-path:/usr/local/bundle
    ports:
      - "8080:3000"
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:8.0.3
    ports:
      - "3206:3306"
    volumes:
      - mysql-data:/var/lib/mysql/data
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=admin"

volumes:
  mysql-data:
  bundle-path:

