version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    container_name: "book_shelf"
    tty: true
    stdin_open: true
    volumes:
      - .:/book_shelf
      - bundle-path:/usr/local/bundle
    ports:
      - "8080:3000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile_db
    # image: mysql:8.0.18
    ports:
      - "3206:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"

volumes:
  mysql-data:
  bundle-path:

