FROM node:13.0.1 as node
FROM ruby:2.6.3
ENV LANG="C.UTF-8" \
    YARN_VERSION="1.19.1"
COPY --from=node /opt/yarn-v$YARN_VERSION /opt/yarn
COPY --from=node /usr/local/bin/node /usr/local/bin

RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       mysql-client \
       vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /rails6_test
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem install bundler -v 2.0.2 \
  && bundle install
COPY . .
# CMD ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
EXPOSE 8080
