FROM node:12.13.1 as node
FROM ruby:2.6.5
ENV LANG="C.UTF-8" \
  YARN_VERSION="1.19.1" \
  TZ="Asia/Tokyo"
COPY --from=node /opt/yarn-v$YARN_VERSION /opt/yarn
COPY --from=node /usr/local/bin/node /usr/local/bin

RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  less \
  default-mysql-client \
  vim \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /book_shelf
COPY Gemfile* ./
#RUN gem install bundler -v 2.0.2 \
RUN  bundle install
RUN  yarn install
COPY . .
EXPOSE 8080
